version: '3.7'
services:

  caddy:
#    image: caddy:latest
    container_name: caddy
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${DATADIR:-/data}/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ${DATADIR:-/data}/caddy/data:${DATADIR:-/data}
      - ${DATADIR:-/data}/caddy/config:/config
      - ${DATADIR:-/data}/caddy/ssl/:/var/lib/caddy
    networks:
      - searcch-frontend-local-dev-net

  searcch-frontend-local-dev:
    image: searcch-frontend-local-dev
    container_name: searcch-frontend-local-dev
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.debug
    env_file:
      - env/searcch-frontend-local-dev.env
    ports:
      - 127.0.0.1:3000:3000
    networks:
      - searcch-frontend-local-dev-net

networks:
  searcch-frontend-local-dev-net:
    name: searcch-frontend-local-dev-net
